# Generated by Django 5.0.3 on 2024-03-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0002_supermercado2_delete_supermercado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supermercado2',
            new_name='Supermercado',
        ),
    ]
