# Generated by Django 5.0.3 on 2024-03-14 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0003_rename_supermercado2_supermercado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermercado',
            name='preço',
            field=models.IntegerField(null=None),
        ),
    ]
