# Generated by Django 5.0.3 on 2024-03-14 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0004_alter_supermercado_preço'),
    ]

    operations = [
        migrations.AddField(
            model_name='supermercado',
            name='categoria',
            field=models.TextField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='supermercado',
            name='produto',
            field=models.TextField(default='none', max_length=50),
        ),
        migrations.AddField(
            model_name='supermercado',
            name='quantidade',
            field=models.IntegerField(default='none', null=None),
        ),
        migrations.AlterField(
            model_name='supermercado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
