# Generated by Django 5.0.3 on 2024-03-14 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0005_supermercado_categoria_supermercado_produto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermercado',
            name='quantidade',
            field=models.IntegerField(default='none'),
        ),
    ]
