# Generated by Django 5.0.3 on 2024-03-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0009_alter_supermercado_preço_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermercado',
            name='preço',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='supermercado',
            name='quantidade',
            field=models.IntegerField(default=1),
        ),
    ]
