# Generated by Django 5.0.3 on 2024-03-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0010_alter_supermercado_preço_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermercado',
            name='quantidade',
            field=models.IntegerField(default=None),
        ),
    ]
