# Generated by Django 5.0.3 on 2024-03-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercado', '0014_alter_supermercado_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermercado',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
